# Generated by Django 4.2.5 on 2023-10-10 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineNotes', '0002_category_note_due_date_note_finished_note_owner_and_more'),
    ]

    operations = [
    ]
