# Generated by Django 4.2.5 on 2023-10-26 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineNotes', '0005_alter_note_created_at_alter_note_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='due_date',
            field=models.DateTimeField(default=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
