# Generated by Django 4.2.5 on 2023-10-27 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineNotes', '0006_alter_note_created_at_alter_note_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(default=True),
        ),
    ]
