# Generated by Django 4.2.5 on 2023-10-27 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineNotes', '0007_alter_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
